### PR TITLE
fix(tx): Remove invalid anchor nesting

### LINKED ISSUE #222: Correct invalid nesting anchor tags when listing transactions
The `AccountTransactionsTable`, `TokenTransactionsTable`, and `Ledger` components all use nested `<a>` tags.  This is invalid HTML and React will throw warnings.  Instead a technique needs to be used where an element is positioned absolute and all "nested" links sit on top of it.

The approach is detailed here. https://bdwm.be/html5-alternative-nested-anchor-tags/

Ex.

``` tsx
<li key={tx.hash}
  className={`transaction-li tx-type ${tx.type}`}
>
  <Link to={`/transactions/${tx.hash}`} className="transaction-whole" />
  <div className="upper">
      //...
  </div>
  <div className="details">
    <a href="whatever">Whatever</a>
    //...
  </div>
</li>
```

```scss
li.transaction-li {
  a {
    position: relative;
    z-index: 10;
  }

  a.transaction-whole {
    position: absolute;
    z-index: 5;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
  }
}
```

### PR DESCRIPTION
**Pull request by ckniffen**
## High Level Overview of Change

The AccountTransactionsTable, TokenTransactionsTable, and Ledger components all used nested <a> tags.  React throws warnings because this is "invalid" html.  The solution is to position an anchor on top of the content and then move any nested anchors on top of that.

Fixes #222

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

## Test Plan

Go to the transaction tables and see if not clicking a link takes you to the transaction and any green links like like those to accounts work.

### CODE REVIEW

File: src/containers/Accounts/AccountTransactionsTable/index.js [hunk 1]
```diff
@@ -64,43 +64,42 @@ export const AccountTxTable = (props) => {
...
           success ? 'success' : 'fail'
         }`}
       >
-        <Link to={`/transactions/${tx.hash}`}>
-          <div className="upper">
-            <div className="col-account">
-              <div className="transaction-address" title={tx.account}>
-                {tx.account}
-              </div>
+        <Link to={`/transactions/${tx.hash}`} className="mask-overlay" />
```
Comment (ckniffen) [inline src/containers/Accounts/AccountTransactionsTable/index.js:71]: All of this was just moving the content out of the `<Link>` component and adding `className="mask-overlay"` to the `<Link>`

**Comment by shawnxie999** [comment]
Looks good. Ill update my PR https://github.com/ripple/explorer/pull/270 after this merges

**Review by shawnxie999 — APPROVED** [review]

**Review by jonathanlei — APPROVED** [review]
