### PR TITLE
fix(transaction): Details page had displayed `{{code}}` for failures

### LINKED ISSUE #236: The details tabs for transactions that fail contain erroneous {{code}}
The summary for failed transactions contain unevaluated `{{code}}` text.

```
This transaction failed with a status code of {{code}}tecINSUF_RESERVE_OFFER, and validated in ledger [73492249](https://livenet.xrpl.org/ledgers/73492249) on August 5, 2022 at 4:46:30 PM UTC
```

 Example Transaction: https://livenet.xrpl.org/transactions/887F024573D3FC9990B80DAE0D3FE95D4C106C400895002436241E85A8C4C31C/detailed

Screen Shot 2022-08-12 at 6 25 34 PM

### PR DESCRIPTION
**Pull request by ckniffen**
## High Level Overview of Change

The tecCode was appended instead of being incorporated into the translation.

Closes #236

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

### TypeScript/Hooks Update

- [ ] Updated files to React Hooks
- [ ] Updated files to TypeScript

### Before
Screen Shot 2022-08-12 at 6 25 34 PM

### After
Screen Shot 2022-08-12 at 6 25 14 PM

### CODE REVIEW

File: src/containers/Transactions/DetailTab.jsx [hunk 1]
```diff
@@ -20,21 +21,21 @@ class DetailTab extends Component {
...
     if (TransactionResult === SUCCESSFULL_TRANSACTION) {
       line1 = t('successful_transaction')
     } else {
       line1 = (
-        <>
-          {t('fail_transaction')}
-          <span className="tx-result fail">{TransactionResult}</span>
-        </>
+        <Trans i18nKey="fail_transaction" values={{ code: TransactionResult }}>
+          <span className="tx-result fail">{{ code }}</span>
```
Comment (mvadari) [inline src/containers/Transactions/DetailTab.jsx:32]: Why create a separate variable instead of doing this?
```suggestion
          <span className="tx-result fail">{{ '' }}</span>
```

Comment (ckniffen) [reply src/containers/Transactions/DetailTab.jsx:32]: I did not see that as an option in the react-i18n. I will try that out

Comment (mvadari) [reply src/containers/Transactions/DetailTab.jsx:32]: Oh, I see what's happening - you're passing in an object. This is confusing to read, I suggested doing this instead:
```suggestion
          <span className="tx-result fail">{ { code: '' } }</span>
```
(and same spacing for the other places where you place in a constructed object

Comment (ckniffen) [reply src/containers/Transactions/DetailTab.jsx:32]: I am actually not placing in an object.  It is doing interpolation when i18n-next evaluates it.  Type checking gets in the way and thinks it is ts code.

Comment (ckniffen) [reply src/containers/Transactions/DetailTab.jsx]: > Why create a separate variable instead of doing this?

`<span className="tx-result fail">{{ '' }}</span>` turns into `<span className="tx-result fail"/>` due to linter but works.

`<span className="tx-result fail">{{ code: '' }}</span>` also works but I found it more confusing.  I added an assertion to make sure the span gets populated with the code properly.

**Review by mvadari — APPROVED** [review]

**Review by pdp2121 — APPROVED** [review]
